#!/bin/bash

PKG=l2tpns
BINDIR=/opt/l2tpns/sbin

case "$1" in
    start)
        printf "\nstarting: $PKG"
        $BINDIR/l2tpns -d
        ;;
    stop)
        printf "\nstopping: $PKG"
	killall l2tpns
        ;;
    *)
        printf "\n\tUsage: $0 < start | stop >\n\n"
        ;;
esac

