#!/bin/bash

PKG=minidlna
BINDIR=/opt/minidlna/sbin

case "$1" in
    start)
        printf "\nstarting: $PKG"
	[ -f /opt/minidlna/etc/minidlna.conf ] || cp /opt/minidlna/etc/config.preconf/minidlna.conf /opt/minidlna/etc/minidlna.conf
        $BINDIR/minidlnad -f /opt/minidlna/etc/minidlna.conf
        ;;
    stop)
        printf "\nstopping: $PKG"
	killall minidlnad
        ;;
    *)
        printf "\n\tUsage: $0 < start | stop >\n\n"
        ;;
esac

