#!/bin/bash

pkg="$1"

PKGDIR=""
[ -d "/var/lib/build/staging/$pkg" ] && PKGDIR="/var/lib/build/staging/$pkg"
[ -d "/var/lib/build/all/$pkg" ] && PKGDIR="/var/lib/build/all/$pkg"


[ "$PKGDIR" ] && [ -f "$PKGDIR/Fetch-source.sh" ] && PATH="/var/lib/build:$PATH" "$PKGDIR/Fetch-source.sh"
