#!/bin/bash

# Maximum number of recursive builds
MR=15
export RECURSIVEBUILD=yes

[ -d /proc/self/fd ] || exit 1
[ -d /dev/fd ] || exit 1
[ -c /dev/null ] || exit 1
[ -c /dev/zero ] || exit 1

if [ "$1" = '-R' ]; then
    export RECURSIVEBUILD=no
    shift
fi
if [ "$1" = '-r' ]; then
    export RECURSIVEBUILD=yes
    shift
fi

if [ -z "$1" ]; then
   echo "Usage: pkg_build [-r|-R] <pkg> ..."
   echo " -r      enable recursive building [default]."
   echo " -R      disable recursive building."
   exit 0
fi

function checkpkg {
    local rc

    rc=0
    while [ "$1" ]; do
	pkg=$(basename $1)
	PKGDIR=""
	[ -d "/var/lib/build/staging/$pkg" ] && PKGDIR="/var/lib/build/staging/$pkg"
	[ -d "/var/lib/build/all/$pkg" ] && PKGDIR="/var/lib/build/all/$pkg"
	if [ -z "$PKGDIR" ]; then
	    echo "/var/lib/build/all/$pkg does not exist"
	    rc=1
	fi
	shift
    done
    return $rc
}

checkpkg $@ || exit 1

mkdir -p /var/tmp/install
mkdir -p /var/tmp/src
mkdir -p /var/spool/src
mkdir -p /var/spool/pkg
mkdir -p /var/log/build
mkdir -p /var/log/config

while [ "$1" ]; do
    n=0
    pkg=$(basename $1)
    shift
    
    rm -rf "/var/tmp/install/$pkg"
    
    /var/lib/build/pkg_uninstall
    [ -d "/var/lib/build/staging/$pkg" ] && export PKGDIR="/var/lib/build/staging/$pkg"
    [ -d "/var/lib/build/all/$pkg" ] && export PKGDIR="/var/lib/build/all/$pkg"
    DEPA=$(grep pkg_install $PKGDIR/Build.sh|wc -l)
    DEPB=$(grep "untar " $PKGDIR/Build.sh|cut -d ' ' -f 1,2|sort|uniq|wc -l)
    MR=$[ DEPA+DEPB+10 ]
    cd $PKGDIR
    
    while true; do
	/var/lib/build/pkg_src_fetch $pkg
	rm -f /var/log/build/$pkg.log
        # Save current stdout to file descriptor 3, and redirect stdout to tee
	exec 3>&1 > >(tee -a "/var/log/build/$pkg.log")
	
	echo "Building $pkg from $PKGDIR"
	PATH="/var/lib/build:$PATH" ./Build.sh 2>&1
	rc=$?
	if [ $rc != 0 ]; then
	    if [ "$RECURSIVEBUILD" = yes ]; then
		if [ $rc = 2 ]; then
		    n=$[ n+1 ]
		    if [ $n -lt $MR ]; then
			exec 1>&3 3>&-
			continue
		    fi
		    echo "ATTN: Maximum number of recursive builds ($MR) exceeded!"
		    echo "ATTN: Last build was \'$pkg\'."
		fi
	    fi
	    echo "ERROR: Build unsuccessful [$rc]. See /var/log/build/$pkg.log"
	else
	    echo "$pkg done!"
	fi
	break
    done
	
    # Restore stdout and close file descriptor 3
    exec 1>&3 3>&-
done
