#!/bin/bash

rc=0
while [ "$1" ]; do
    pkg=$(basename $1)
    pkgfile=""
    [ -f "/var/spool/pkg/$pkg.tar.gz" ] && pkgfile="/var/spool/pkg/$pkg.tar.gz"
    [ -f "/var/spool/pkg/$pkg.tgz" ] && pkgfile="/var/spool/pkg/$pkg.tgz"
    
    if [ -z "$pkgfile" ]; then
	echo "$pkg not found in spool"
	rc=1
	if [ "$RECURSIVEBUILD" = yes ]; then
	    pkg_build $pkg
	fi
    fi
    shift
done
exit $rc
