#!/bin/bash

STATE=/var/state/installed_files
STATEPKGS=/var/state/installed_pkgs
TMPFILE=/tmp/installed_files_tmp.$$
MOVEFILES=/var/state/movedfiles.tar

rm -f $TMPFILE
touch $TMPFILE
trap "rm -f $TMPFILE" EXIT

mkdir -p /var/state

cd /
# remount w
if [ -s $STATE ]; then
    tac $STATE|while read f; do
        if [ -d "$f" ]; then
	    rmdir $f &> /dev/null
	    continue
	fi
        rm -f "$f" || (echo "$f" >> $TMPFILE)
    done
fi
cp -f $TMPFILE $STATE
rm -f $TMPFILE
rm -f $STATEPKGS
if [ -f $MOVEFILES ]; then
    if tar xUf $MOVEFILES; then
	rm -f $MOVEFILES
    else
	echo "Failed restore backup of files in $MOVEFILES !!"
    fi
fi
# remount r
