#!/bin/bash

[ -d /proc/self/fd ] || exit 1
[ -d /dev/fd ] || exit 1
[ -c /dev/null ] || exit 1
[ -c /dev/zero ] || exit 1

if [ -z "$1" ]; then
   echo "Usage: pkg_build <pkg> ..."
   exit 0
fi

function checkpkg {
    local rc

    rc=0
    while [ "$1" ]; do
	pkg=$(basename $1)
	PKGDIR=""
	[ -d "/var/lib/build/staging/$pkg" ] && PKGDIR="/var/lib/build/staging/$pkg"
	[ -d "/var/lib/build/$pkg" ] && PKGDIR="/var/lib/build/$pkg"
	if [ -z "$PKGDIR" ]; then
	    echo "/var/lib/build/$pkg does not exist"
	    rc=1
	fi
	shift
    done
    return $rc
}

checkpkg $@ || exit 1

mkdir -p /var/tmp/install
mkdir -p /var/tmp/src
mkdir -p /var/spool/src
mkdir -p /var/spool/pkg
mkdir -p /var/log/build

while [ "$1" ]; do
    pkg=$(basename $1)
    shift
    
    rm -rf "/var/tmp/install/$pkg"
    
    /var/lib/build/pkg_uninstall
    [ -d "/var/lib/build/staging/$pkg" ] && export PKGDIR="/var/lib/build/staging/$pkg"
    [ -d "/var/lib/build/$pkg" ] && export PKGDIR="/var/lib/build/$pkg"
    cd $PKGDIR
    echo "Building $pkg from $PKGDIR" | tee /var/log/build/$pkg.log
    PATH="/var/lib/build:$PATH" ./Build.sh 2>&1 | tee -a /var/log/build/$pkg.log
    rc=$?
    if [ $rc != 0 ]; then
	echo "ERROR: Build unsuccessful [$rc]. See /var/log/build/$pkg.log"
    else
	echo "$pkg done!"
    fi
done
