#!/bin/bash

PKG=dovecot
BINDIR=/opt/dovecot/sbin

case "$1" in
    start)
        printf "\nstarting: $PKG"
        $BINDIR/dovecot
        ;;
    stop)
        printf "\nstopping: $PKG"
	kill $(cat /var/run/dovecot/master.pid)
        ;;
    *)
        printf "\n\tUsage: $0 < start | stop >\n\n"
        ;;
esac

