#!/bin/bash

PKG=exim
BINDIR=/opt/exim/bin

case "$1" in
    start)
        printf "\nstarting: $PKG"
        $BINDIR/exim -bd -q15m
        ;;
    stop)
        printf "\nstopping: $PKG"
	killall exim
        ;;
    *)
        printf "\n\tUsage: $0 < start | stop >\n\n"
        ;;
esac

